version: '3.4'

services:
  sqlserverdb:
    image: mcr.microsoft.com/azure-sql-edge:latest
  
  rabbitmq:
    image: rabbitmq:management
  
  experimentdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4
  
  sqlserveragent.api:
    image: sqlserveragent.api
    build:
      context: .
      dockerfile: Services/SQLServerAgent.API/Dockerfile
    depends_on: 
      - sqlserverdb
      - rabbitmq

  configagent.api:
    image: configagent.api
    build:
      context: .
      dockerfile: Services/ConfigAgent.API/Dockerfile
    depends_on: 
      - rabbitmq
      - sqlserveragent.api
  
  experimentagent.api:
    image: experimentagent.api
    build:
      context: .
      dockerfile: Services/ExperimentAgent.API/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserveragent.api
      - experimentdb

volumes:
  sqlserver-db:
  experiment-agent-db:
  pgadmin_data: