version: '3.4'

services:
  sqlserverdb:
    container_name: sqlserverdb
    environment:
      SA_PASSWORD: ""
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-db:/var/opt/mssql
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  
  experimentdb:
    container_name: experimentdb
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=CacheDiveExperimentDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - experiment-agent-db:/var/opt/postgresql
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  sqlserveragent.api:
    container_name: sqlserveragent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection="
      - "EventBusSettings:HostAddress="
    restart: always
    ports:
      - "8001:80"

  redisagent.api:
    container_name: redisagent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "8002:80"
  
  memcachedagent.api:
    container_name: memcachedagent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "8003:80"

  configagent.api:
    container_name: configagent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress="
    restart: always
    ports:
      - "8004:80"
  
  experimentagent.api:
    container_name: experimentagent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection="
      - "EventBusSettings:HostAddress="
    restart: always
    ports:
      - "8005:80"
  
  identityagent.api:
    container_name: identityagent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection="
    restart: always
    ports:
      - "8006:80"
    volumes:
      - .src/SharedConfig:/app/SharedConfig
  
  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .src/SharedConfig:/app/SharedConfig